"""add server defaults for booleans

Revision ID: 3c4eeb62ed1f
Revises: afeaee7eac5f
Create Date: 2026-03-04 19:01:22.352885

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c4eeb62ed1f'
down_revision: str | Sequence[str] | None = 'afeaee7eac5f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
